name: crypto_portfolio_tracker
description: "Crypto Portfolio Tracker - Track your portfolio like a pro"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
